config/routes.rb
Rails.application.routes.draw do
  Blacklight::Marc.add_routes(self)
  root to: "catalog#index"

  blacklight_for :catalog
  devise_for :users

  get "shelf/nearby", to: "shelf#nearby", as: "shelf_nearby"
  get "browse/fondslist", to: "browse#fondslist", as: "browse_fondslist"

  get "collections", to: "browse#collections", as: "list_collections"

  get "browse/authors", to: "browse#authors", as: "browse_authors"
  get "browse/directors", to: "browse#directors", as: "browse_directors"
  get "browse/languages", to: "browse#languages", as: "browse_languages"
  get "browse/library_collections", to: "browse#library_collections", as: "browse_library_collections"
  get "browse/av_collections", to: "browse#av_collections", as: "browse_av_collections"
  get "browse/digital_collections", to: "browse#digital_collections", as: "browse_digital_collections"

  get "db/fa/:lookup", to: "falookup#lookup", as: "falookup_lookup"
  get "falist/:id", to: "falist#index", as: "falist_index"

  get "vis/dr_timeline/data/:collection/:year/:month", to: "drtimeline#get_data_by_date", as: "drtimeline_data_by_date"
  get "vis/dr_timeline/data/:collection/dates", to: "drtimeline#get_dates_for_collection", as: "drtimeline_dates_for_collection"
  get "vis/dr_timeline", to: "drtimeline#index", as: "drtimeline_index"

  get "browse/privacy_policy", to: "browse#privacy_policy", as: "privacy_policy"

end

app/views/shared/_ajax_modal.html.erb
<div class="modal fade" id="ajax-modal" tabindex="-1" role="dialog" aria-labelledby="modal menu" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        </div>
    </div>
</div>

app/views/shared/_feedback.html.erb
<div id="theme-options" class="hidden-xs">
    <div id="body-options">
        <div id="color-options">
            <h2 class="no-margin-top">Color Selector</h2>
            <a href="javascript:void(0);" rel="style-blue.css" class="color-box color-blue">blue</a>
            <a href="javascript:void(0);" rel="style-blue2.css" class="color-box color-blue2">blue2</a>
            <a href="javascript:void(0);" rel="style-blue3.css" class="color-box color-blue3">blue3</a>
            <a href="javascript:void(0);" rel="style-blue4.css" class="color-box color-blue4">blue4</a>
            <a href="javascript:void(0);" rel="style-blue5.css" class="color-box color-blue5">blue5</a>
            <a href="javascript:void(0);" rel="style-green.css" class="color-box color-green">green</a>
            <a href="javascript:void(0);" rel="style-green2.css" class="color-box color-green2">green2</a>
            <a href="javascript:void(0);" rel="style-green3.css" class="color-box color-green3">green3</a>
            <a href="javascript:void(0);" rel="style-green4.css" class="color-box color-green4">green4</a>
            <a href="javascript:void(0);" rel="style-green5.css" class="color-box color-green5">green5</a>
            <a href="javascript:void(0);" rel="style-red.css" class="color-box color-red">red</a>
            <a href="javascript:void(0);" rel="style-red2.css" class="color-box color-red2">red2</a>
            <a href="javascript:void(0);" rel="style-red3.css" class="color-box color-red3">red3</a>
            <a href="javascript:void(0);" rel="style-fuchsia.css" class="color-box color-fuchsia">fuchsia</a>
            <a href="javascript:void(0);" rel="style-pink.css" class="color-box color-pink">pink</a>
            <a href="javascript:void(0);" rel="style-yellow.css" class="color-box color-yellow">yellow</a>
            <a href="javascript:void(0);" rel="style-yellow2.css" class="color-box color-yellow2">yellow2</a>
            <a href="javascript:void(0);" rel="style-orange.css" class="color-box color-orange">orange</a>
            <a href="javascript:void(0);" rel="style-orange2.css" class="color-box color-orange2">orange2</a>
            <a href="javascript:void(0);" rel="style-orange3.css" class="color-box color-orange3">orange3</a>
            <a href="javascript:void(0);" rel="style-violet.css" class="color-box color-violet">violet</a>
            <a href="javascript:void(0);" rel="style-violet2.css" class="color-box color-violet2">violet2</a>
            <a href="javascript:void(0);" rel="style-violet3.css" class="color-box color-violet3">violet3</a>
            <a href="javascript:void(0);" rel="style-gray.css" class="color-box color-gray">gray</a>
            <a href="javascript:void(0);" rel="style-aqua.css" class="color-box color-aqua">aqua</a>
        </div>
        <div>
            <h2>Header Style</h2>
            <form id="header-option">
                <div class="radio">
                    <input type="radio" name="headerRadio" id="header-full-radio" value="header-full" checked>
                    <label for="header-full-radio">Light Header</label>
                </div>
                <div class="radio">
                    <input type="radio" name="headerRadio" id="header-full-dark-radio" value="header-full-dark">
                    <label for="header-full-dark-radio">Dark Header</label>
                </div>
                <div class="radio">
                    <input type="radio" name="headerRadio" id="no-header-radio" value="no-header">
                    <label for="no-header-radio">No Header (Navbar mode)</label>
                </div>
            </form>
        </div>
        <div>
            <h2>Navbar Style</h2>
            <form id="navbar-option">
                <div class="radio">
                    <input type="radio" name="navbarRadio" id="navbar-light-radio" value="navbar-light">
                    <label for="navbar-light-radio">Light Color</label>
                </div>
                <div class="radio">
                    <input type="radio" name="navbarRadio" id="navbar-dark-radio" value="navbar-dark" checked>
                    <label for="navbar-dark-radio">Dark Color</label>
                </div>
                <div class="radio">
                    <input type="radio" name="navbarRadio" id="navbar-inverse-radio" value="navbar-inverse">
                    <label for="navbar-inverse-radio">Primary Color</label>
                </div>
            </form>
        </div>
        <div id="width-options">
            <h2>Container Selector</h2>
            <div class="btn-group">
                <form>
                    <input type="checkbox" name="full-width-checkbox" data-label-width="80" data-label-text="Full Width" checked>
                </form>
            </div>
        </div>
    </div>
    <div id="icon-options">
        <i class="fa fa-commenting-o fa-2x fa-flip-horizontal"></i>
    </div>
</div>

app/views/shared/_flash_messages.erb
<div class="container">
  <div class="col-md-12">
    <div id="main-flashes">
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<aside id="footer-widgets">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                    <p><strong>VERA AND DONALD BLINKEN OPEN SOCIETY ARCHIVES</strong><br/>
                       <i class="fa fa-map-marker"></i> <strong>ADDRESS</strong> H-1051 Budapest, Arany János u. 32.<br/>
                       <i class="fa fa-calendar"></i> <strong>OPENING HOURS</strong> Monday-Friday 10AM-5:45PM</p>
            </div>
            <div class="col-md-4">
                    <p><i class="fa fa-phone"></i> <strong>TEL</strong> +36-1-327-3250<br/>
                       <i class="fa fa-fax"></i> <strong>FAX</strong> +36-1-327-3260<br/>
                       <i class="fa fa-envelope-o"></i> <strong>EMAIL</strong> <a href="mailto:info@osaarchivum.org">info@osaarchivum.org</a></p>
            </div>
            <div class="col-md-2">
                <div class="ceu-logo"><a href="http://www.ceu.hu" target="_blank"><img src="<%= asset_path 'ceu-logo.png' %>" /></a></div>
            </div>
        </div> <!-- row -->
    </div> <!-- container -->
</aside> <!-- footer-widgets -->

<footer id="footer">
    <p>&copy; 2015 <a href="#">OSA Archivum</a></p>
</footer>

app/views/shared/_header.html.erb
<header id="header-full-top" class="hidden-xs header-full">
    <div class="container">
        <div class="header-full-title">
          <div class="header-image">
            <a href="http://www.osaarchivum.org"><img src="<%= asset_path 'osa_logo.png' %>" /></a>
          </div>
          <div class="header-title">
            <a href="/"><h1>catal<span>o</span>g</h1></a>
          </div>
        </div>
    </div> <!-- container -->
</header> <!-- header-full -->

app/views/shared/_header_home.erb
<header id="header-full-top" class="hidden-xs header-full">
    <div class="container">
        <div class="header-full-title">
          <a href="/"><img class="logo" src="<%= asset_path 'osa_logo.png' %>" /></a>
          <h1>catal<span>o</span>g</h1>
        </div>

        <nav class="top-nav">
            <!--
            <ul class="top-nav-social hidden-sm">
                <li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#" class="google-plus"><i class="fa fa-desktop"></i></a></li>
            </ul>

            <div class="dropdown">
                <%= render :partial => 'shared/user_links' %>
            </div>

            <div class="dropdown">
                <%= render :partial => 'shared/login' %>
            </div>
            -->
        </nav>
    </div> <!-- container -->
</header> <!-- header-full -->

app/views/shared/_login.html.erb
<% if has_user_authentication_provider? %>
    <% if current_user %>
      <%= link_to t('blacklight.header_links.logout'), destroy_user_session_path %>
    <% unless current_user.to_s.blank? -%>
      <%= link_to current_user, edit_user_registration_path %>
    <% end %>
    <% else %>
      <%= link_to t('blacklight.header_links.login'), new_user_session_path %>
    <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-static-top navbar-default navbar-header-full navbar-dark yamm" role="navigation" id="header">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
            <a id="ar-brand" class="navbar-brand inv-header-title" href="/">
              <h1>catal<span>o</span>g</h1>
            </a>
        </div> <!-- navbar-header -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
            <ul class="nav navbar-nav menu-list">
                <li class="menu">
                  <% if current_page?(controller: 'browse', action: 'fondslist') %>
                    <span class="menu-icon current">
                      OSA Collections
                    </span>
                  <% else %>
                    <a href="/browse/fondslist" class="menu-icon" >
                      OSA Collections
                    </a>
                  <% end %>
                </li>
                <li class="dropdown">
                    <% if current_page?(controller: 'browse', action: 'authors') %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                        Authors [A - Z]
                      </a>
                    <% elsif current_page?(controller: 'browse', action: 'directors') %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                        Directors [A - Z]
                      </a>
                    <% elsif current_page?(controller: 'browse', action: 'languages') %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                        Languages [A - Z]
                      </a>
                    <% elsif current_page?(controller: 'browse', action: 'library_collections') %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                        Library Special Collections
                      </a>
                    <% elsif current_page?(controller: 'browse', action: 'av_collections') %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                        Audio Visual Special Collections
                      </a>
                    <% elsif current_page?(controller: 'browse', action: 'digital_collections') %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                        Digital Collections
                      </a>
                    <% else %>
                      <a href="javascript:void(0);" class="dropdown-toggle menu-icon" data-toggle="dropdown">
                        Browse
                      </a>
                    <% end %>
                  <ul class="dropdown-menu dropdown-menu-left">
                    <li>
                      <a href="<%= browse_authors_path %>">Authors</a>
                    </li>
                    <li>
                      <a href="<%= browse_directors_path %>">Directors</a>
                    </li>
                    <li>
                      <a href="<%= browse_languages_path %>">Languages</a>
                    </li>
                    <li>
                      <a href="<%= browse_library_collections_path %>">Library Special Collections</a>
                    </li>
                    <li>
                      <a href="<%= browse_av_collections_path %>">Audio Visual Special Collections</a>
                    </li>
                    <li>
                      <a href="<%= browse_digital_collections_path %>">Digital Collections</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <% if current_page?(controller: 'drtimeline', action: 'index') %>
                    <a href="javascript:void(0);" class="dropdown-toggle menu-icon current" data-toggle="dropdown">
                      Digital Collection Timeline
                    </a>
                  <% else %>
                    <a href="javascript:void(0);" class="dropdown-toggle menu-icon" data-toggle="dropdown">
                      Visualization
                    </a>
                  <% end %>
                  <ul class="dropdown-menu dropdown-menu-left">
                    <li>
                      <a href="<%= drtimeline_index_path %>">Digital Collection Timeline</a>
                    </li>
                  </ul>
                </li>
                <%= render_nav_actions do |config, action|%>
                  <li class="menu">
                    <%= action %>
                  </li>
                <% end %>
              </ul>
              <ul class="nav navbar-nav menu-list pull-right">
                <li class="menu">
                  <% if current_page?(controller: 'browse', action: 'privacy_policy') %>
                      <span class="menu-icon current">
                        Privacy Policy
                      </span>
                  <% else %>
                      <a href="/browse/privacy_policy" class="menu-icon" >
                        Privacy Policy
                      </a>
                  <% end %>
                </li>
              </ul>
            </ul>
        </div><!-- navbar-collapse -->

    </div>
</nav>

app/views/shared/_navbar_start.html.erb
<nav class="navbar navbar-static-top navbar-default navbar-header-full navbar-dark yamm" role="navigation" id="header">
    <div class="container">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
            <a id="ar-brand" class="navbar-brand hidden-lg hidden-md hidden-sm" href="index.html">OSA <span>Catalog</span></a>
        </div> <!-- navbar-header -->

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav menu-list">
                <li class="menu">
                  <% if current_page?(controller: 'browse', action: 'fondslist') %>
                    <span class="menu-icon current">
                      OSA Collections
                    </span>
                  <% else %>
                    <a href="/browse/fondslist" class="menu-icon" >
                      OSA Collections
                    </a>
                  <% end %>
                </li>
                <li class="dropdown">
                  <a href="javascript:void(0);" class="dropdown-toggle menu-icon" data-toggle="dropdown">
                    <% if current_page?(controller: 'browse', action: 'authors') %>
                      Authors [A - Z]
                    <% elsif current_page?(controller: 'browse', action: 'directors') %>
                      Directors [A - Z]
                    <% elsif current_page?(controller: 'browse', action: 'languages') %>
                      Languages [A - Z]
                    <% elsif current_page?(controller: 'browse', action: 'library_collections') %>
                      Library Special Collections
                    <% elsif current_page?(controller: 'browse', action: 'av_collections') %>
                      Audio Visual Special Collections
                    <% else %>
                      Browse
                    <% end %>
                  </a>
                  <ul class="dropdown-menu dropdown-menu-left">
                    <li>
                      <a href="<%= browse_authors_path %>">Authors</a>
                    </li>
                    <li>
                      <a href="<%= browse_directors_path %>">Directors</a>
                    </li>
                    <li>
                      <a href="<%= browse_languages_path %>">Languages</a>
                    </li>
                    <li>
                      <a href="<%= browse_library_collections_path %>">Library Special Collections</a>
                    </li>
                    <li>
                      <a href="<%= browse_av_collections_path %>">Audio Visual Special Collections</a>
                    </li>
                    <li>
                      <a href="<%= browse_digital_collections_path %>">Digital Collections</a>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="javascript:void(0);" class="dropdown-toggle menu-icon" data-toggle="dropdown">
                    Visualization
                  </a>
                  <ul class="dropdown-menu dropdown-menu-left">
                    <li>
                      <a href="<%= drtimeline_index_path %>">Digital Collection Timeline</a>
                    </li>
                  </ul>
                </li>
                <%= render_nav_actions do |config, action|%>
                  <li class="menu">
                    <%= action %>
                  </li>
                <% end %>
              </ul>
              <ul class="nav navbar-nav menu-list pull-right">
                <li class="menu">
                  <% if current_page?(controller: 'browse', action: 'privacy_policy') %>
                      <span class="menu-icon current">
                        Privacy Policy
                      </span>
                  <% else %>
                      <a href="/browse/privacy_policy" class="menu-icon" >
                        Privacy Policy
                      </a>
                  <% end %>
                </li>
              </ul>
        </div><!-- navbar-collapse -->

    </div>
</nav>

app/views/shared/_slidebar.html.erb
<div class="sb-slidebar sb-right">
    <h2 class="slidebar-header no-margin-bottom">Information</h2>
    <p><span class="info-record-origin">OSA Collections Catalog</span> offers an integrated search function built on
    three major databases: standard bibliographic library records, film
    library bibliographic records and archival item/ folder level
    descriptions along with rich contextual descriptions (ISADG, ISAAR etc.)</p>
    <p>The <span class="info-record-origin">OSA Library Collections</span> are described using English language MARC
    bibliographic records for both periodicals and reference books related
    to Cold War, Human Rights and the archival/library profession.
    Information about books and journals, including Russian periodicals, are
    searchable through the integrated search, with the exception of
    Eastern-European and Central Asian language periodicals, whose
    cataloging are still in progress. These Eastern-European language
    periodicals will temporarily be accessible to users
    <a href="http://fa.osaarchivum.org/library/periodicals?idx=Languages" target="_blank">here</a>.
    Additionally, Special Collections are not yet accessible on the integrated search.
    Short summaries and inventories could be accessed from
    <a href="http://www.osaarchivum.org/library" target="_blank">here.</a></p>
    <p>The <span class="info-record-origin">OSA Archival Holdings</span> are fully available through the integrated
    search. The Catalog is in English, with original titles in different
    languages included in the folder and item-level descriptions. Contextual
    information about particular collections (fonds), sub-collections
    (sub-fonds) and records groups (series) is provided as part of the
    archival hierarchy. The connections between digitized and born-digital
    holdings are established by cross-reference links which appear in the
    series level descriptions of archival records. The digital repository,
    containing itemized descriptions on digital objects is searchable
    <a href="http://www.osaarchivum.org/greenfield/repository" target="_blank">here</a>.
    For a detailed overview of the scope and diversity of our holdings,
    please consult the <a href="<%= browse_fondslist_path %>" target="_blank">OSA Collections list</a>.</p>
    <p>The <span class="info-record-origin">OSA Film Library</span> contains approximately 4000 documentary and
    propaganda films as well as selected fiction. The catalog is regularly
    updated to reflect recent acquisitions. OSA Film Library is available
    for on-site viewing in the OSA Research Room. In addition to the Film
    Library, OSA has rich audiovisual collections in the OSA Archival
    Holdings (see above).</p>
</div> <!-- sb-slidebar sb-right -->

app/views/shared/_user_links.erb
  <%= render_nav_actions do |config, action|%>
    <%= action %>
  <% end %>