config/routes.rb
Rails.application.routes.draw do
  Blacklight::Marc.add_routes(self)
  root to: "catalog#index"

  blacklight_for :catalog
  devise_for :users

  get "shelf/nearby", to: "shelf#nearby", as: "shelf_nearby"
  get "browse/fondslist", to: "browse#fondslist", as: "browse_fondslist"

  get "collections", to: "browse#collections", as: "list_collections"

  get "browse/authors", to: "browse#authors", as: "browse_authors"
  get "browse/directors", to: "browse#directors", as: "browse_directors"
  get "browse/languages", to: "browse#languages", as: "browse_languages"
  get "browse/library_collections", to: "browse#library_collections", as: "browse_library_collections"
  get "browse/av_collections", to: "browse#av_collections", as: "browse_av_collections"
  get "browse/digital_collections", to: "browse#digital_collections", as: "browse_digital_collections"

  get "db/fa/:lookup", to: "falookup#lookup", as: "falookup_lookup"
  get "falist/:id", to: "falist#index", as: "falist_index"

  get "vis/dr_timeline/data/:collection/:year/:month", to: "drtimeline#get_data_by_date", as: "drtimeline_data_by_date"
  get "vis/dr_timeline/data/:collection/dates", to: "drtimeline#get_dates_for_collection", as: "drtimeline_dates_for_collection"
  get "vis/dr_timeline", to: "drtimeline#index", as: "drtimeline_index"

  get "browse/privacy_policy", to: "browse#privacy_policy", as: "privacy_policy"

end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  layout 'osacatalog'

  def index
  end

  def fondslist
  end

  def collections
    if params[:theme]
      theme = params[:theme]
    else
      theme = "All"
    end

    @collectionslist = CollectionsStructure.new(theme).collectionslist
    render json: @collectionslist
  end

  def authors
    @creators = BrowseList.new('author_browse').browselist
    render creators: @creators
  end

  def directors
    @directors = BrowseList.new('director_browse').browselist
    render directors: @directors
  end

  def languages
    @languages = BrowseList.new('language_facet').browselist
    render directors: @languages
  end

  def library_collections
    @library_collections = BrowseList.new('library_collection', 'browselist_all').browselist
    render library_collections: @library_collections
  end

  def av_collections
    @av_collections = BrowseList.new('av_collection', 'browselist_all').browselist
    render av: @av_collections
  end

  def digital_collections
    @digital_collections = BrowseList.new('digital_collection', 'browselist_all').browselist
    render digital_collections: @digital_collections
  end

  def privacy_policy
  end

end

app/helpers/browse_helper.rb
module BrowseHelper
  def link_to_callnumber_browse(document)
    link_to(
      document[:call_number].first,
      shelf_nearby_path(
        start: document[:id]
      ),
      class: "btn btn-sm btn-default collapsed",
      id: "callnumber-browse",
      "aria-labelledby" => "callnumber-browse",
       data: { behavior: "embed-browse",
               start: document[:id],
               embed_viewport: "#callnumber",
               url: shelf_nearby_path(
                 start: document[:id],
                 view: 'gallery'
               )
             }
    )
  end
end

app/views/browse/authors.html.erb
<div class="container margin-bottom">
    <div class="col-md-12">
      <div class="item-toolbar row">
        <div class="item-pagination col-sm-5">
          <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
        </div>
      </div>
      <div class="row">
        <h3>List of Authors</h3>
        <%= @creators %>
      </div>
    </div>
</div>

app/views/browse/av_collections.html.erb
<div class="container margin-bottom">
    <div class="col-md-12">
      <div class="item-toolbar row">
        <div class="item-pagination col-sm-5">
          <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
        </div>
      </div>
      <div class="row">
        <h3>List of Audio Visual Special Collections</h3>
        <%= @av_collections %>
      </div>
    </div>
</div>

app/views/browse/digital_collections.html.erb
<div class="container margin-bottom">
    <div class="col-md-12">
      <div class="item-toolbar row">
        <div class="item-pagination col-sm-5">
          <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
        </div>
      </div>
      <div class="row">
        <h3>List of Digital Collections</h3>
        <%= @digital_collections %>
      </div>
    </div>
</div>

app/views/browse/directors.html.erb
<div class="container margin-bottom">
    <div class="col-md-12">
      <div class="item-toolbar row">
        <div class="item-pagination col-sm-5">
          <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
        </div>
      </div>
      <div class="row">
        <h3>List of Directors</h3>
        <%= @directors %>
      </div>
    </div>
</div>

app/views/browse/fondslist.html.erb
<div class="container margin-bottom">
  <div class="item-toolbar row">
    <div class="item-pagination col-sm-2">
      <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
    </div>
    <div class="item-menu col-sm-10">
      <ul class="item-tools">
        <li class="item-tools-listitem">
          <select class="form-control" id="archivalUnitThemes">
            <option value="All">- All Themes -</option>
            <option value="Communism and Cold War">Communism and Cold War</option>
            <option value="Human Rights">Human Rights</option>
            <option value="Civil Society">Civil Society</option>
          </select>
        </li>
        <li class="item-tools-listitem">
          <a id="filter-theme" class="btn btn-danger btn-sm">Filter Themes</a>
        </li>
        <li class="item-tools-listitem">
          <a id="jstree-open" class="btn btn-default btn-sm"><i class="fa fa-plus"></i> Open all</a>
        </li>
        <li class="item-tools-listitem">
          <a id="jstree-close" class="btn btn-default btn-sm"><i class="fa fa-minus"></i> Close all</a>
        </li>
      </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <h3>List of Fonds</h3>
      <div id="fondslist_all" class="fondslist-full"></div>
    </div>
  </div>
</div>

app/views/browse/languages.html.erb
<div class="container margin-bottom">
    <div class="col-md-12">
      <div class="item-toolbar row">
        <div class="item-pagination col-sm-5">
          <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
        </div>
      </div>
      <div class="row">
        <h3>List of Languages</h3>
        <%= @languages %>
      </div>
    </div>
</div>

app/views/browse/library_collections.html.erb
<div class="container margin-bottom">
    <div class="col-md-12">
      <div class="item-toolbar row">
        <div class="item-pagination col-sm-5">
          <a class="btn btn-sm btn-danger back-to-results" href="<%= catalog_index_path %>">Back to Catalog</a>
        </div>
      </div>
      <div class="row">
        <h3>List of Library Special Collections</h3>
        <%= @library_collections %>
      </div>
    </div>
</div>

app/views/browse/privacy_policy.html.erb
<div class="container margin-bottom">
  <div class="row">
    <div id="content" class="col-sm-12">
      <h3 class="page-heading">Privacy Policy</h3>
      <p>The website Blinken OSA Catalog is operated by the Vera and Donald Blinken Open Society Archives (Blinken OSA),
        an organizational unit of Central European University (in Hungarian: Közép-európai Egyetem), as part of its
        domain www.osaarchivum.org. Blinken OSA informs its visitors herewith about its data processing practices,
        the organizational and technical measures it introduced in order to protect personal data, and the users’
        possibilities for remedies.</p>

      <h3>1. Data Controller</h3>
      <p>Közép-európai Egyetem (registration number: FI 272861, seat: 1051 Budapest, Nádor u. 9.)</p>

      <h3>2. Data Protection Officer</h3>
      <p>The Data Protection Officer of Közép-európai Egyetem, concerning electronic documents, is Szilárd Bedecs,
        IT Director; available in matters concerning data processing by Blinken OSA at
        <a href="mailto:dataprotection@osaarchivum.org">dataprotection@osaarchivum.org</a>.</p>

      <h3>3. Scope of Processed Personal Data</h3>
      <p>Anyone can visit http://catalog.osaarchivum.org/ without providing any personal data beyond those recorded
        automatically and necessary for technical reasons.</p>
        In order to maintain the technical connection, the website http://catalog.osaarchivum.org/ sends so-called
        cookies to the user’s computer, and these are automatically deleted when the browser is closed.</p>
        http://catalog.osaarchivum.org/ lets Google Analytics, YouTube and Twitter install cookies capable of
        individual identification on the user’s computer. Google Analytics serves the purpose of analyzing the
        website’s visitor statistics, while the connection with YouTube and Twitter is the consequence of making
        Blinken OSA accessible through these services. Google, YouTube and Twitter are data controllers independent
        from Blinken OSA, who – through the cookies installed by them – can determine the users’ profile and analyze
        their activities on the Internet.</p>
        Visitors of http://catalog.osaarchivum.org/ can delete cookies installed on their computer any time during
        browsing. Deleting the cookies installed by our website does not limit the further use of the website,
        only search history is deleted on such occasions.</p>

      <h3>4. The Purpose of Data Processing</h3>
      <p>Recording and storing data relating to the time of the visit, the IP address and the data of the browser and
        the operating system are characteristics of the system, processing thereof is indispensable, and serves
        statistical purposes and ensures the availability of the service.</p>

      <h3>5. The Legal Basis of Data Processing</h3>
      <p>In compliance with the provisions of Act CVIII of 2001 on Certain Aspects of Electronic Commerce and
        Information Society Services, the data controller is authorized to process personal data indispensable for
        providing the service. The operator of the website processes data necessary for providing the service,
        for the necessary extent and time period.</p>

      <h3>6. Period for Storing Personal Data</h3>
      <p>The personal data processed by http://catalog.osaarchivum.org/ (necessary for maintaining the service technically)
        are automatically deleted when closing the browser, or within one month the latest.</p>

      <h3>7. Scope of Those Accessing Personal Data</h3>
      <p>Access to data recorded in the course of the technical operating of the website are accessible solely to staff
      members of the data controller. The operator of the website does not employ intermediaries as data processors.
      The data controller does not transfer personal data to third persons, except for transfers prescribed by law.
      About cookies installed on the user’s computer by external data controllers, see section 2 above.
      Please note that clickable web addresses (links) available on our website, if not pointing to pages within
      the domain www.osaarchivum.org, belong to the sphere of responsibility of other data controllers.</p>

      <h3>8. Data Security Measures</h3>
      <p>Personal data relating to visiting the website are stored on our own servers operating in Blinken OSA’s
        server room, guarded 24 hours a day.</p>

      <h3>9. Rights of Users Relating to the Processing of Their Personal Data</h3>
      <p>If you find that the operator of the website http://catalog.osaarchivum.org/ has infringed your rights to
        protection of personal data, please contact us at <a href="mailto:dataprotection@osaarchivum.org">
        dataprotection@osaarchivum.org</a> so that we can redress the possible infringement.</p>
      <p>We inform our users that they can file complaints at the National Authority for Data Protection and
        Freedom of Information (<a href="http://www.naih.hu" target="_blank">www.naih.hu</a>) or file a claim with a civil court. The details of this and the data
        controller’s legal obligations are included in Act CXII of 2011 on the Right of Informational
        Self-Determination and on Freedom of Information as well as in Section 13/A of Act CVIII of
        2001 on Certain Aspects of Electronic Commerce and Information Society Services.</p>
      <p>Should you need further information about the processing of personal data,
        please contact us at <a href="mailto:dataprotection@osaarchivum.org">dataprotection@osaarchivum.org.</a></p><br/>
    </div>
  </div>
</div>